apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.test.serviceName }}
spec:
  type: {{ .Values.test.servicetype}}
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80